### PR TITLE
Tried to Clean and Organise the Readme file

### PR DESCRIPTION
**Pull request by ThenoobMario**
Made a separate guide to set up Firebase in the app and linked it to the Readme. Also edited Heroku guide for typos and in general formatting. 

Also ticked the multiple pages option in Further work since it was completed :)

### CODE REVIEW

**Review by smaranjitghose — APPROVED** [review]

**Comment by smaranjitghose** [comment]
give @ThenoobMario 50 points

**Comment by smaranjitghose** [comment]
# Additional Suggestion:
@ThenoobMario Before giving a PR try to make a squash commit of all your commits related to this PR

**Comment by ThenoobMario** [comment]
Okay will keep that in mind the next time I open a PR. Thank you

**Comment by smaranjitghose** [comment]
give @ThenoobMario 25 points

**Pull request merged**
