### PR TITLE
Updated GKE guide file

### PR DESCRIPTION
**Pull request by rohankumawat**
Issue #2 
Added a folder named images.
Updated the GCP guide markdown file.

### CODE REVIEW

**Comment by smaranjitghose** [comment]
All images should be inside assets folder. And a subsequent .slugignore and .dockerignore should be added for them

**Comment by smaranjitghose** [comment]
The images are not loading

**Comment by smaranjitghose** [comment]
The content changes are totally meaningless

**Comment by rohankumawat** [comment]
Can you please specify by which content you found this meaningless?
It'll kind of help me to solve this thing!
And yes, what to change?

**Comment by rohankumawat** [comment]
> Can you please specify by which content you found this meaningless?
> It'll kind of help me to solve this thing!
> And yes, what to change?

Now, do I have to create another branch and then do this task?

**Pull request closed without merging**
